steps:

- task: dotNetCoreCLI@1
  inputs:
    command: restore
    projects: "**/*.csproj"
  displayName: dotnet restore

- task: dotNetCoreCLI@1
  inputs:
    command: build
    projects: "**/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

- task: dotNetCoreCLI@1
  inputs:
    command: test 
    projects: "**/*Tests/*.csproj"
    arguments: --configuration release
  displayName: dotnet build

- task: dotNetCoreCLI@1
  inputs:
    command: publish
    arguments: --configuration release --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true
  displayName: dotnet publish

- task: publishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: drop
    ArtifactType: Container
  displayName: Publish the artifacts
  
- task: AzureRmWebAppDeployment@2
  inputs:
    ConnectedServiceName: $(System.TeamProject)
    ResourceGroupName: $(System.TeamProject)
    WebAppName: $(System.TeamProject)
    Package: $(build.artifactstagingdirectory)/**/*.zip
    TakeAppOfflineFlag: true